# Generated by Django 2.2.3 on 2020-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolar_Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data inicial')),
                ('atual', models.DateField(auto_now=True, verbose_name='Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name_dolar', models.CharField(max_length=50)),
                ('buy_dolar', models.FloatField(null=True)),
                ('sell_dolar', models.FloatField(null=True)),
                ('variacao_dolar', models.FloatField(null=True)),
                ('data_dolar', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Euro_Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data inicial')),
                ('atual', models.DateField(auto_now=True, verbose_name='Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name_euro', models.CharField(max_length=50)),
                ('buy_euro', models.FloatField(null=True)),
                ('sell_euro', models.FloatField(null=True)),
                ('variacao_euro', models.FloatField(null=True)),
                ('data_euro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Libra_Esterlina_Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data inicial')),
                ('atual', models.DateField(auto_now=True, verbose_name='Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name_libra', models.CharField(max_length=50, verbose_name='Libra')),
                ('buy_libra', models.FloatField(null=True)),
                ('sell_libra', models.FloatField(null=True)),
                ('variacao_libra', models.FloatField(null=True)),
                ('data_libra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Peso_Argentino_Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data inicial')),
                ('atual', models.DateField(auto_now=True, verbose_name='Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name_peso', models.CharField(max_length=50)),
                ('buy_peso', models.FloatField(null=True)),
                ('sell_peso', models.FloatField(null=True)),
                ('variacao_peso', models.FloatField(null=True)),
                ('data_peso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Real_Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atual', models.DateField(auto_now=True, verbose_name='Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
